"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { useSession } from "next-auth/react";
import AppShell from "@/components/layout/AppShell";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, CardBody, CardHeader, CardTitle } from "@/components/ui/Card";
import { Dialog } from "@/components/ui/Dialog";
import { Input, Select, Textarea } from "@/components/ui/Input";
import { PageHeader } from "@/components/ui/PageHeader";
import { Tabs } from "@/components/ui/Tabs";
import { useToast } from "@/components/ui/Toast";
import { api } from "@/utils/trpc";
import { ArrowLeftIcon, CheckCircleIcon, ClockIcon, PlusIcon, UserMinusIcon, UserPlusIcon } from "@heroicons/react/24/outline";

const ROUTINES = ["BEFORE_CAMP", "DAILY", "SPECIFIC_DAY", "BEFORE_PROGRAMME", "DURING_PROGRAMME", "AFTER_PROGRAMME", "BEFORE_MEAL", "DURING_MEAL", "AFTER_MEAL", "END_OF_DAY", "ARRIVAL", "AFTER_CHECKOUT", "AFTER_CAMP", "ONE_TIME"] as const;
const ROLE_KINDS = ["HEAD", "ASSISTANT_HEAD", "LEAD", "MEMBER"] as const;

function localDateKey(date = new Date()) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
}
function lines(value: string) { return value.split("\n").map((item) => item.trim()).filter(Boolean); }
function label(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase()); }

export default function DepartmentWorkspacePage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const { data: session } = useSession();
  const organizationId = (session?.user as any)?.organizationId ?? "";
  const date = localDateKey();
  const { data: camp } = api.camp.getActiveCamp.useQuery({ organizationId }, { enabled: !!organizationId });
  const query = api.departmentOperations.get.useQuery({ departmentId: id, date }, { enabled: !!id });
  const department = query.data;

  return (
    <AppShell area="admin">
      <button type="button" onClick={() => router.push("/admin/departments")} className="mb-3 inline-flex items-center gap-1 text-sm font-medium text-txt-secondary hover:text-accent-700"><ArrowLeftIcon className="h-4 w-4" /> Departments</button>
      <PageHeader title={department?.name ?? "Department"} description={department?.purpose ?? "Department operations workspace"} />
      {!department || !camp ? <div className="py-20 text-center text-sm text-txt-secondary">Loading department workspace…</div> : (
        <Tabs tabs={[
          { label: "Overview", content: <Overview department={department} /> },
          { label: "People & roles", content: <PeopleRoles department={department} organizationId={organizationId} campId={camp.id} /> },
          { label: "Responsibilities", content: <Guide department={department} /> },
          { label: "Checklist", content: <Checklist department={department} /> },
          { label: "History", content: <History department={department} date={date} /> },
        ]} />
      )}
    </AppShell>
  );
}

function Overview({ department }: { department: any }) {
  const toast = useToast();
  const utils = api.useUtils();
  const [edit, setEdit] = useState(false);
  const [name, setName] = useState(department.name);
  const [purpose, setPurpose] = useState(department.purpose ?? "");
  const [description, setDescription] = useState(department.description ?? "");
  const [status, setStatus] = useState<"ACTIVE" | "INACTIVE">(department.status);
  const [parentDepartmentId, setParentDepartmentId] = useState(department.parentDepartmentId ?? "");
  const departmentOptions = api.departmentOperations.list.useQuery({ campId: department.campId, date: localDateKey(), includeInactive: true });
  const update = api.departmentOperations.updateDepartment.useMutation({ onSuccess: () => { toast.success("Department updated."); setEdit(false); utils.departmentOperations.get.invalidate(); }, onError: (e) => toast.error(e.message) });
  const executions = department.checklistExecutions ?? [];
  const completed = executions.filter((item: any) => item.status === "COMPLETED").length;
  const overdue = executions.filter((item: any) => item.status === "OVERDUE").length;
  const headPosition = department.positions.find((position: any) => position.roleKind === "HEAD");
  const head = headPosition?.assignments[0]?.staff;
  const assistant = department.positions.find((position: any) => position.roleKind === "ASSISTANT_HEAD")?.assignments[0]?.staff;
  const supervisedRoles = department.positions.filter((position: any) => position.parentPositionId === headPosition?.id).map((position: any) => position.name);
  const memberIds = new Set(department.positions.flatMap((position: any) => position.assignments.map((assignment: any) => assignment.staff.id)));
  return <div className="space-y-6">
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <Metric label="Today completed" value={`${completed}/${executions.length}`} /><Metric label="Overdue" value={overdue} /><Metric label="Active people" value={memberIds.size} /><Metric label="Active roles" value={department.positions.filter((p: any) => p.status === "ACTIVE").length} />
    </div>
    <div className="grid gap-5 lg:grid-cols-[2fr_1fr]">
      <Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Department definition</CardTitle><Button size="sm" variant="secondary" onClick={() => setEdit(true)}>Edit</Button></div></CardHeader><CardBody className="space-y-5 text-sm"><Section title="Purpose" values={[department.purpose || "Not defined"]} /><Section title="Description" values={[department.description || "Not defined"]} /><Section title="Reports to" values={[headPosition?.parentPosition?.name || department.parentDepartment?.name || "Camp leadership"]} /><Section title="Supervises" values={[...department.childDepartments.map((child: any) => child.name), ...supervisedRoles]} /></CardBody></Card>
      <Card><CardHeader><CardTitle>Leadership</CardTitle></CardHeader><CardBody className="space-y-4 text-sm"><PersonLabel label="Department leader" person={head} /><PersonLabel label="Assistant leader" person={assistant} /><div><span className="text-xs text-txt-muted">Status</span><p><Badge tone={department.status === "ACTIVE" ? "success" : "neutral"}>{department.status}</Badge></p></div></CardBody></Card>
    </div>
    <Dialog open={edit} onClose={() => setEdit(false)} title="Edit department"><div className="space-y-4"><Input label="Name" value={name} onChange={(e) => setName(e.target.value)} /><Textarea label="Purpose" rows={3} value={purpose} onChange={(e) => setPurpose(e.target.value)} /><Textarea label="Description" rows={4} value={description} onChange={(e) => setDescription(e.target.value)} /><Select label="Reports to / parent" value={parentDepartmentId} onChange={(e) => setParentDepartmentId(e.target.value)}><option value="">No parent</option>{departmentOptions.data?.filter((item) => item.id !== department.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select label="Status" value={status} onChange={(e) => setStatus(e.target.value as "ACTIVE" | "INACTIVE")}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></Select><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setEdit(false)}>Cancel</Button><Button loading={update.isPending} onClick={() => update.mutate({ id: department.id, name, purpose, description, parentDepartmentId: parentDepartmentId || null, status })}>Save</Button></div></div></Dialog>
  </div>;
}

function PeopleRoles({ department, organizationId, campId }: { department: any; organizationId: string; campId: string }) {
  const toast = useToast(); const utils = api.useUtils();
  const [assignRole, setAssignRole] = useState<any>(null); const [staffId, setStaffId] = useState(""); const [secondary, setSecondary] = useState(false); const [endDate, setEndDate] = useState(""); const [reason, setReason] = useState("");
  const [roleOpen, setRoleOpen] = useState(false); const [roleName, setRoleName] = useState(""); const [roleKind, setRoleKind] = useState<(typeof ROLE_KINDS)[number]>("MEMBER"); const [parentPositionId, setParentPositionId] = useState("");
  const [editRole, setEditRole] = useState<any>(null); const [editPurpose, setEditPurpose] = useState(""); const [editResponsibilities, setEditResponsibilities] = useState(""); const [editAuthority, setEditAuthority] = useState(""); const [editSuccess, setEditSuccess] = useState("");
  const [peopleSearch, setPeopleSearch] = useState("");
  const [roleFilter, setRoleFilter] = useState("");
  const [moveAssignment, setMoveAssignment] = useState<any>(null); const [targetPositionId, setTargetPositionId] = useState(""); const [moveReason, setMoveReason] = useState("");
  const teachers = api.staff.adminList.useQuery({ organizationId, campId, type: "TEACHER", status: "APPROVED", limit: 100 });
  const volunteers = api.staff.adminList.useQuery({ organizationId, campId, type: "VOLUNTEER", status: "APPROVED", limit: 100 });
  const allDepartments = api.departmentOperations.list.useQuery({ campId, date: localDateKey(), includeInactive: false });
  const staff = [...(teachers.data?.items ?? []), ...(volunteers.data?.items ?? [])].sort((a, b) => `${a.firstName} ${a.lastName}`.localeCompare(`${b.firstName} ${b.lastName}`));
  const assign = api.departmentOperations.assignPerson.useMutation({ onSuccess: () => { toast.success(secondary ? "Secondary department assigned." : "Primary department assigned."); setAssignRole(null); setStaffId(""); setSecondary(false); setEndDate(""); setReason(""); utils.departmentOperations.get.invalidate(); }, onError: (e) => toast.error(e.message) });
  const remove = api.departmentOperations.removePerson.useMutation({ onSuccess: () => { toast.success("Person removed; their user account and history were preserved."); utils.departmentOperations.get.invalidate(); }, onError: (e) => toast.error(e.message) });
  const move = api.departmentOperations.movePerson.useMutation({ onSuccess: () => { toast.success("Person moved to the selected role."); setMoveAssignment(null); setTargetPositionId(""); setMoveReason(""); utils.departmentOperations.get.invalidate(); }, onError: (e) => toast.error(e.message) });
  const createRole = api.departmentOperations.createRole.useMutation({ onSuccess: () => { toast.success("Role created."); setRoleOpen(false); setRoleName(""); utils.departmentOperations.get.invalidate(); }, onError: (e) => toast.error(e.message) });
  const updateRole = api.departmentOperations.updateRole.useMutation({ onSuccess: () => { toast.success("Role guide updated."); setEditRole(null); utils.departmentOperations.get.invalidate(); }, onError: (e) => toast.error(e.message) });
  function closeAssignment() { setAssignRole(null); setStaffId(""); setSecondary(false); setEndDate(""); setReason(""); }
  function openAssignment(position: any) { closeAssignment(); setAssignRole(position); }
  function openRoleGuide(position: any) { setEditRole(position); setEditPurpose(position.purpose ?? ""); setEditResponsibilities(position.responsibilities.join("\n")); setEditAuthority(position.authority.join("\n")); setEditSuccess(position.successMeasures.join("\n")); }
  return <div className="space-y-4">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex-1"><p className="text-sm text-txt-secondary">Roles are durable positions; people can be replaced without rewriting the role or its guide.</p><div className="mt-3 grid max-w-2xl gap-3 sm:grid-cols-[1fr_220px]"><Input aria-label="Search people and roles" placeholder="Search people, email, phone, or roles" value={peopleSearch} onChange={(e) => setPeopleSearch(e.target.value)} /><Select aria-label="Filter by role type" value={roleFilter} onChange={(e) => setRoleFilter(e.target.value)}><option value="">All role types</option>{ROLE_KINDS.map((kind) => <option key={kind} value={kind}>{label(kind)}</option>)}</Select></div></div><Button onClick={() => setRoleOpen(true)}><PlusIcon className="h-4 w-4" /> Add role</Button></div>
    <div className="space-y-3">{department.positions.filter((position: any) => (!roleFilter || position.roleKind === roleFilter) && (!peopleSearch || `${position.name} ${position.assignments.map((assignment: any) => `${assignment.staff.firstName} ${assignment.staff.lastName} ${assignment.staff.email ?? ""} ${assignment.staff.phone ?? ""}`).join(" ")}`.toLowerCase().includes(peopleSearch.toLowerCase()))).map((position: any) => <Card key={position.id}><CardBody className="space-y-3"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="font-semibold text-txt-primary">{position.name}</h3><Badge tone={position.roleKind === "HEAD" ? "info" : position.roleKind === "ASSISTANT_HEAD" ? "attention" : "neutral"}>{label(position.roleKind)}</Badge></div><p className="mt-1 text-xs text-txt-secondary">{position.purpose || "No role purpose defined."}</p></div><Button size="sm" variant="secondary" onClick={() => openAssignment(position)}><UserPlusIcon className="h-4 w-4" /> Assign</Button></div>
      <div className="flex justify-end"><Button size="sm" variant="ghost" onClick={() => openRoleGuide(position)}>Edit role guide</Button></div>{position.assignments.length ? <div className="grid gap-2 sm:grid-cols-2">{position.assignments.map((assignment: any) => <div key={assignment.id} className="flex items-center justify-between rounded-xl bg-surface-raised p-3 text-sm"><div><p className="font-medium text-txt-primary">{assignment.staff.firstName} {assignment.staff.lastName}</p><p className="text-xs text-txt-secondary">{assignment.staff.type} · {assignment.staff.departmentId === department.id ? "Primary" : "Secondary"}{assignment.endDate ? ` · until ${new Date(assignment.endDate).toLocaleDateString()}` : ""}</p></div><div className="flex"><button type="button" aria-label={`Move ${assignment.staff.firstName} to another role`} onClick={() => setMoveAssignment(assignment)} className="rounded-lg p-2 text-txt-secondary hover:bg-surface-hover"><UserPlusIcon className="h-4 w-4" /></button><button type="button" aria-label={`Remove ${assignment.staff.firstName} from ${position.name}`} onClick={() => remove.mutate({ assignmentId: assignment.id })} className="rounded-lg p-2 text-danger-600 hover:bg-danger-50"><UserMinusIcon className="h-4 w-4" /></button></div></div>)}</div> : <p className="rounded-lg border border-dashed border-border-default p-3 text-xs text-txt-muted">Vacant role</p>}
    </CardBody></Card>)}</div>
    <Dialog open={!!assignRole} onClose={closeAssignment} title={`Assign ${assignRole?.name ?? "role"}`}><div className="space-y-4"><Select label="Person" value={staffId} onChange={(e) => setStaffId(e.target.value)}><option value="">Select teacher or volunteer</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.firstName} {person.lastName} · {person.type}</option>)}</Select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={secondary} onChange={(e) => setSecondary(e.target.checked)} /> Secondary department assignment</label><p className="text-xs text-txt-secondary">A primary department is the person&apos;s main team. Secondary assignments add another department without replacing it.</p>{secondary && <Input label="Ends on (optional)" type="datetime-local" value={endDate} onChange={(e) => setEndDate(e.target.value)} />}<Textarea label="Reason / note" value={reason} onChange={(e) => setReason(e.target.value)} rows={2} /><div className="flex justify-end gap-2"><Button variant="secondary" onClick={closeAssignment}>Cancel</Button><Button disabled={!staffId} loading={assign.isPending} onClick={() => assign.mutate({ positionId: assignRole.id, staffId, secondary, endDate: endDate ? new Date(endDate).toISOString() : undefined, reason: reason || undefined })}>Assign person</Button></div></div></Dialog>
    <Dialog open={roleOpen} onClose={() => setRoleOpen(false)} title="Add department role"><div className="space-y-4"><Input label="Role name" value={roleName} onChange={(e) => setRoleName(e.target.value)} /><Select label="Role type" value={roleKind} onChange={(e) => setRoleKind(e.target.value as any)}>{ROLE_KINDS.map((kind) => <option key={kind} value={kind}>{label(kind)}</option>)}</Select><Select label="Reports to role" value={parentPositionId} onChange={(e) => setParentPositionId(e.target.value)}><option value="">No parent role</option>{department.positions.map((position: any) => <option key={position.id} value={position.id}>{position.name}</option>)}</Select><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setRoleOpen(false)}>Cancel</Button><Button disabled={!roleName.trim()} loading={createRole.isPending} onClick={() => createRole.mutate({ departmentId: department.id, name: roleName, roleKind, parentPositionId: parentPositionId || null, responsibilities: [], authority: [], successMeasures: [] })}>Create role</Button></div></div></Dialog>
    <Dialog open={!!editRole} onClose={() => setEditRole(null)} title={`Edit ${editRole?.name ?? "role"} guide`}><div className="space-y-4"><Textarea label="Purpose" value={editPurpose} onChange={(e) => setEditPurpose(e.target.value)} rows={2} /><Textarea label="Responsibilities" value={editResponsibilities} onChange={(e) => setEditResponsibilities(e.target.value)} rows={6} helpText="One item per line" /><Textarea label="Authority" value={editAuthority} onChange={(e) => setEditAuthority(e.target.value)} rows={4} helpText="One item per line" /><Textarea label="Success measures" value={editSuccess} onChange={(e) => setEditSuccess(e.target.value)} rows={4} helpText="One item per line" /><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setEditRole(null)}>Cancel</Button><Button loading={updateRole.isPending} onClick={() => updateRole.mutate({ id: editRole.id, purpose: editPurpose || null, responsibilities: lines(editResponsibilities), authority: lines(editAuthority), successMeasures: lines(editSuccess) })}>Save role guide</Button></div></div></Dialog>
    <Dialog open={!!moveAssignment} onClose={() => setMoveAssignment(null)} title={`Move ${moveAssignment?.staff?.firstName ?? "person"}`}><div className="space-y-4"><Select label="New department role" value={targetPositionId} onChange={(e) => setTargetPositionId(e.target.value)}><option value="">Choose a role</option>{allDepartments.data?.map((unit) => <optgroup key={unit.id} label={unit.name}>{unit.positions.map((position: any) => <option key={position.id} value={position.id}>{position.name}</option>)}</optgroup>)}</Select><Textarea label="Reason / note" value={moveReason} onChange={(e) => setMoveReason(e.target.value)} rows={2} /><p className="text-xs text-txt-secondary">The previous assignment is closed and preserved in history. The user account is unchanged.</p><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setMoveAssignment(null)}>Cancel</Button><Button disabled={!targetPositionId} loading={move.isPending} onClick={() => move.mutate({ assignmentId: moveAssignment.id, targetPositionId, reason: moveReason || undefined })}>Move person</Button></div></div></Dialog>
  </div>;
}

function Guide({ department }: { department: any }) {
  const toast = useToast(); const utils = api.useUtils();
  const [responsibilities, setResponsibilities] = useState(department.responsibilities.join("\n")); const [authority, setAuthority] = useState(department.authority.join("\n")); const [success, setSuccess] = useState(department.successMeasures.join("\n")); const [relationships, setRelationships] = useState(department.workingRelationships.join("\n"));
  useEffect(() => { setResponsibilities(department.responsibilities.join("\n")); setAuthority(department.authority.join("\n")); setSuccess(department.successMeasures.join("\n")); setRelationships(department.workingRelationships.join("\n")); }, [department]);
  const update = api.departmentOperations.updateDepartment.useMutation({ onSuccess: () => { toast.success("Department guide updated."); utils.departmentOperations.get.invalidate(); }, onError: (e) => toast.error(e.message) });
  return <div className="grid gap-5 lg:grid-cols-2"><GuideEditor title="Responsibilities" value={responsibilities} onChange={setResponsibilities} /><GuideEditor title="Authority" value={authority} onChange={setAuthority} /><GuideEditor title="Success measures" value={success} onChange={setSuccess} /><GuideEditor title="Working relationships" value={relationships} onChange={setRelationships} /><div className="lg:col-span-2 flex justify-end"><Button loading={update.isPending} onClick={() => update.mutate({ id: department.id, responsibilities: lines(responsibilities), authority: lines(authority), successMeasures: lines(success), workingRelationships: lines(relationships) })}>Save department guide</Button></div></div>;
}

function Checklist({ department }: { department: any }) {
  const toast = useToast(); const utils = api.useUtils();
  const [open, setOpen] = useState(false); const [editItem, setEditItem] = useState<any>(null); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [routine, setRoutine] = useState<(typeof ROUTINES)[number]>("DAILY"); const [assignmentType, setAssignmentType] = useState<"EVERYONE" | "ROLE" | "PERSON">("EVERYONE"); const [positionId, setPositionId] = useState(""); const [assignedStaffId, setAssignedStaffId] = useState(""); const [dueTime, setDueTime] = useState(""); const [specificDate, setSpecificDate] = useState("");
  function closeForm() { setOpen(false); setEditItem(null); setTitle(""); setDescription(""); setRoutine("DAILY"); setAssignmentType("EVERYONE"); setPositionId(""); setAssignedStaffId(""); setDueTime(""); setSpecificDate(""); }
  function edit(item: any) { setEditItem(item); setTitle(item.title); setDescription(item.description ?? ""); setRoutine(item.routine); setAssignmentType(item.assignmentType); setPositionId(item.positionId ?? ""); setAssignedStaffId(item.assignedStaffId ?? ""); setDueTime(item.dueTime ?? ""); setSpecificDate(item.specificDate ? localDateKey(new Date(item.specificDate)) : ""); setOpen(true); }
  const create = api.departmentOperations.createChecklistItem.useMutation({ onSuccess: () => { toast.success("Checklist item created."); closeForm(); utils.departmentOperations.get.invalidate(); }, onError: (e) => toast.error(e.message) });
  const update = api.departmentOperations.updateChecklistItem.useMutation({ onSuccess: () => { toast.success("Checklist item updated without changing history."); closeForm(); utils.departmentOperations.get.invalidate(); }, onError: (e) => toast.error(e.message) });
  const settings = api.departmentOperations.updateDepartment.useMutation({ onSuccess: () => { toast.success("Checklist permissions updated."); utils.departmentOperations.get.invalidate(); }, onError: (e) => toast.error(e.message) });
  const members = department.positions.flatMap((position: any) => position.assignments.map((assignment: any) => assignment.staff)).filter((person: any, index: number, all: any[]) => all.findIndex((x) => x.id === person.id) === index);
  const grouped = useMemo(() => Object.entries(Object.groupBy(department.checklistItems as any[], (item: any) => item.routine)), [department.checklistItems]);
  return <div className="space-y-5">
    <Card><CardBody className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Toggle label="Members can add items" checked={department.allowMembersAddChecklistItems} onChange={(value) => settings.mutate({ id: department.id, allowMembersAddChecklistItems: value })} /><Toggle label="Members can edit items" checked={department.allowMembersEditChecklistItems} onChange={(value) => settings.mutate({ id: department.id, allowMembersEditChecklistItems: value })} /><Toggle label="Members can deactivate items" checked={department.allowMembersDeactivateChecklistItems} onChange={(value) => settings.mutate({ id: department.id, allowMembersDeactivateChecklistItems: value })} /><Toggle label="Enable routine checklists" checked={department.enableRoutineChecklists} onChange={(value) => settings.mutate({ id: department.id, enableRoutineChecklists: value })} /><Toggle label="Enable programme-triggered tasks" checked={department.enableProgrammeTriggeredTasks} onChange={(value) => settings.mutate({ id: department.id, enableProgrammeTriggeredTasks: value })} /><Toggle label="Enable deadline reminders" checked={department.enableDeadlineReminders} onChange={(value) => settings.mutate({ id: department.id, enableDeadlineReminders: value })} /></CardBody></Card>
    <div className="flex items-center justify-between"><p className="text-sm text-txt-secondary">Definitions create immutable daily executions; edits affect only future work.</p><Button onClick={() => setOpen(true)}><PlusIcon className="h-4 w-4" /> Add checklist item</Button></div>
    {grouped.map(([routineName, items]) => <section key={routineName} className="space-y-2"><h3 className="text-sm font-semibold text-txt-primary">{label(routineName)}</h3>{(items ?? []).map((item: any) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border border-border-default bg-surface p-3"><div><p className="text-sm font-medium text-txt-primary">{item.title}</p><p className="text-xs text-txt-secondary">{item.assignmentType === "EVERYONE" ? "Everyone" : item.position?.name || (item.assignedStaff ? `${item.assignedStaff.firstName} ${item.assignedStaff.lastName}` : "Unassigned")}{item.dueTime ? ` · due ${item.dueTime}` : ""}</p></div><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => edit(item)}>Edit</Button><Button size="sm" variant="secondary" onClick={() => update.mutate({ id: item.id, active: false })}>Deactivate</Button></div></div>)}</section>)}
    <Dialog open={open} onClose={closeForm} title={editItem ? "Edit checklist item" : "Add checklist item"}><div className="space-y-4"><Input label="Task" value={title} onChange={(e) => setTitle(e.target.value)} /><Textarea label="Instructions" value={description} onChange={(e) => setDescription(e.target.value)} rows={2} /><div className="grid gap-3 sm:grid-cols-2"><Select label="Routine" value={routine} onChange={(e) => setRoutine(e.target.value as any)}>{ROUTINES.map((value) => <option key={value} value={value}>{label(value)}</option>)}</Select><Input label="Due time (optional)" type="time" value={dueTime} onChange={(e) => setDueTime(e.target.value)} /></div>{routine === "SPECIFIC_DAY" && <Input label="Specific date" type="date" value={specificDate} onChange={(e) => setSpecificDate(e.target.value)} />}<Select label="Assignment" value={assignmentType} onChange={(e) => setAssignmentType(e.target.value as any)}><option value="EVERYONE">Everyone in department</option><option value="ROLE">Department role</option><option value="PERSON">Specific person</option></Select>{assignmentType === "ROLE" && <Select label="Role" value={positionId} onChange={(e) => setPositionId(e.target.value)}><option value="">Choose role</option>{department.positions.map((position: any) => <option key={position.id} value={position.id}>{position.name}</option>)}</Select>}{assignmentType === "PERSON" && <Select label="Person" value={assignedStaffId} onChange={(e) => setAssignedStaffId(e.target.value)}><option value="">Choose person</option>{members.map((person: any) => <option key={person.id} value={person.id}>{person.firstName} {person.lastName}</option>)}</Select>}<div className="flex justify-end gap-2"><Button variant="secondary" onClick={closeForm}>Cancel</Button><Button disabled={!title.trim() || (routine === "SPECIFIC_DAY" && !specificDate) || (assignmentType === "ROLE" && !positionId) || (assignmentType === "PERSON" && !assignedStaffId)} loading={create.isPending || update.isPending} onClick={() => { const values = { title, description: description || null, routine, assignmentType, positionId: assignmentType === "ROLE" ? positionId : null, assignedStaffId: assignmentType === "PERSON" ? assignedStaffId : null, dueTime: dueTime || null, specificDate: routine === "SPECIFIC_DAY" ? specificDate : null, required: true }; if (editItem) update.mutate({ id: editItem.id, ...values }); else create.mutate({ departmentId: department.id, ...values, description: description || undefined }); }}>{editItem ? "Save changes" : "Create item"}</Button></div></div></Dialog>
  </div>;
}

function History({ department, date }: { department: any; date: string }) {
  const initialFrom = new Date(); initialFrom.setDate(initialFrom.getDate() - 30);
  const toast = useToast(); const [status, setStatus] = useState(""); const [routine, setRoutine] = useState(""); const [positionId, setPositionId] = useState(""); const [completedById, setCompletedById] = useState(""); const [dateFrom, setDateFrom] = useState(localDateKey(initialFrom)); const [dateTo, setDateTo] = useState(date); const [reportOpen, setReportOpen] = useState(false); const [completedWork, setCompletedWork] = useState(""); const [outstandingWork, setOutstandingWork] = useState(""); const [issues, setIssues] = useState(""); const [escalations, setEscalations] = useState(""); const [notes, setNotes] = useState("");
  const people = department.positions.flatMap((position: any) => position.assignments.map((assignment: any) => assignment.staff)).filter((person: any, index: number, all: any[]) => all.findIndex((item) => item.userId === person.userId) === index);
  const history = api.departmentOperations.history.useQuery({ departmentId: department.id, dateFrom, dateTo, status: status as any || undefined, routine: routine as any || undefined, positionId: positionId || undefined, completedById: completedById || undefined });
  const submit = api.departmentOperations.submitReport.useMutation({ onSuccess: () => { toast.success("Department report submitted."); setReportOpen(false); }, onError: (e) => toast.error(e.message) });
  const grouped = Object.entries(Object.groupBy(history.data ?? [], (item: any) => new Date(item.date).toLocaleDateString()));
  return <div className="space-y-5"><div className="flex flex-col gap-3"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Input label="From" type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} /><Input label="To" type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} /><Select label="Status" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{["PENDING", "COMPLETED", "SKIPPED", "OVERDUE"].map((value) => <option key={value}>{value}</option>)}</Select><Select label="Routine" value={routine} onChange={(e) => setRoutine(e.target.value)}><option value="">All routines</option>{ROUTINES.map((value) => <option key={value}>{label(value)}</option>)}</Select><Select label="Role" value={positionId} onChange={(e) => setPositionId(e.target.value)}><option value="">All roles</option>{department.positions.map((position: any) => <option key={position.id} value={position.id}>{position.name}</option>)}</Select><Select label="Completed by" value={completedById} onChange={(e) => setCompletedById(e.target.value)}><option value="">Anyone</option>{people.map((person: any) => <option key={person.userId} value={person.userId}>{person.firstName} {person.lastName}</option>)}</Select></div><div className="flex justify-end"><Button onClick={() => setReportOpen(true)}>Submit department report</Button></div></div>
    {grouped.length === 0 ? <div className="rounded-xl border border-dashed border-border-default p-10 text-center text-sm text-txt-muted">No execution history for these filters.</div> : grouped.map(([day, items]) => { const completed=(items ?? []).filter((x:any)=>x.status==="COMPLETED").length; return <Card key={day}><CardHeader><div className="flex justify-between"><CardTitle>{day}</CardTitle><span className="text-sm font-medium text-txt-secondary">{completed}/{items?.length} completed</span></div></CardHeader><CardBody className="divide-y divide-border-subtle">{(items ?? []).map((item:any)=><div key={item.id} className="grid gap-1 py-3 text-sm sm:grid-cols-[1fr_120px_220px] sm:items-center"><span className="font-medium text-txt-primary">{item.taskTitle}</span><Badge tone={item.status==="COMPLETED"?"success":item.status==="OVERDUE"?"danger":item.status==="SKIPPED"?"warning":"neutral"}>{item.status}</Badge><span className="text-txt-secondary">{item.completedByName || item.skippedByName || "—"}{item.completedAt ? ` · ${new Date(item.completedAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}` : ""}</span></div>)}</CardBody></Card>; })}
    <Dialog open={reportOpen} onClose={() => setReportOpen(false)} title="Department report"><div className="space-y-3"><Textarea label="Completed work" value={completedWork} onChange={(e)=>setCompletedWork(e.target.value)} rows={3} /><Textarea label="Outstanding work" value={outstandingWork} onChange={(e)=>setOutstandingWork(e.target.value)} rows={2} /><Textarea label="Issues" value={issues} onChange={(e)=>setIssues(e.target.value)} rows={2} /><Textarea label="Escalations" value={escalations} onChange={(e)=>setEscalations(e.target.value)} rows={2} /><Textarea label="Notes" value={notes} onChange={(e)=>setNotes(e.target.value)} rows={2} /><div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setReportOpen(false)}>Cancel</Button><Button disabled={!completedWork.trim()} loading={submit.isPending} onClick={()=>submit.mutate({departmentId:department.id,date,completedWork,outstandingWork:outstandingWork||undefined,issues:issues||undefined,escalations:escalations||undefined,notes:notes||undefined})}>Submit report</Button></div></div></Dialog>
  </div>;
}

function Metric({ label: text, value }: { label: string; value: string | number }) { return <Card><CardBody><p className="text-xs text-txt-muted">{text}</p><p className="mt-1 text-2xl font-bold text-txt-primary">{value}</p></CardBody></Card>; }
function Section({ title, values }: { title: string; values: string[] }) { return <section><h3 className="text-xs font-semibold uppercase tracking-wide text-txt-muted">{title}</h3>{values.length ? <ul className="mt-2 space-y-1 text-txt-primary">{values.map((value, index) => <li key={`${value}-${index}`}>{value}</li>)}</ul> : <p className="mt-2 text-txt-muted">None defined</p>}</section>; }
function PersonLabel({ label: text, person }: { label: string; person?: any }) { return <div><span className="text-xs text-txt-muted">{text}</span><p className="font-semibold text-txt-primary">{person ? `${person.firstName} ${person.lastName}` : "Vacant"}</p></div>; }
function GuideEditor({ title, value, onChange }: { title: string; value: string; onChange: (value: string) => void }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardBody><Textarea aria-label={title} rows={10} value={value} onChange={(e) => onChange(e.target.value)} helpText="One item per line" /></CardBody></Card>; }
function Toggle({ label: text, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center justify-between gap-3 text-sm text-txt-primary"><span>{text}</span><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} className="h-5 w-5 rounded border-input-border text-accent-600" /></label>; }
