import { z } from "zod";
import { createTRPCRouter, protectedProcedure } from "../trpc/trpc";
import { prisma } from "../../db";
import { TRPCError } from "@trpc/server";
import { Prisma } from "@prisma/client";
import { assertOrgAdmin, assertOrgAdminOrCampusRep } from "../trpc/scoping";

// Schema for campus data validation
// NOTE: 'slug' is required and must be generated by the UI from the name field and sent as part of the payload.
const campusSchema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters"),
  slug: z.string().min(1, "Slug is required"),
  address: z.string().min(5, "Address must be at least 5 characters"),
  city: z.string().min(2, "City must be at least 2 characters"),
  state: z.string().optional(),
  zipCode: z.string().optional(),
  country: z.string().min(2, "Country must be at least 2 characters"),
  pastor: z.string().nullable().optional(),
  phone: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  active: z.boolean().optional(),
  signupOpen: z.boolean().optional(),
  campusCode: z.string().nullable().optional(),
  displayOrder: z.number().int().optional(),
  organizationId: z.string(),
});

function isUniqueConstraintError(error: unknown): error is Prisma.PrismaClientKnownRequestError {
  return error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002";
}

function formatUniqueErrorMessage(meta: Record<string, unknown> | undefined): string {
  const target = meta?.target;
  const fields = Array.isArray(target) ? target : [];
  if (fields.includes("slug")) {
    return "This campus name/URL is already in use by another organization. Please use a different name.";
  }
  if (fields.includes("name") || fields.includes("Campus_organizationId_name_key")) {
    return "A campus with this name already exists in your organization.";
  }
  return "A campus with this name or URL already exists.";
}

async function assertCampusNameAvailable(
  organizationId: string,
  name: string,
  excludeId?: string
): Promise<void> {
  const existing = await prisma.campus.findFirst({
    where: {
      organizationId,
      name,
      deletedAt: null,
      ...(excludeId ? { NOT: { id: excludeId } } : {}),
    },
  });
  if (existing) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: "A campus with this name already exists in your organization.",
    });
  }
}

async function assertCampusSlugAvailable(slug: string, excludeId?: string): Promise<void> {
  const existing = await prisma.campus.findFirst({
    where: {
      slug,
      deletedAt: null,
      ...(excludeId ? { NOT: { id: excludeId } } : {}),
    },
  });
  if (existing) {
    throw new TRPCError({
      code: "BAD_REQUEST",
      message: "This campus name/URL is already in use by another organization. Please use a different name.",
    });
  }
}

export const campusRouter = createTRPCRouter({
  // Create a new campus
  create: protectedProcedure
    .input(campusSchema)
    .mutation(async ({ input, ctx }) => {
      await assertOrgAdmin(ctx, input.organizationId);

      await assertCampusNameAvailable(input.organizationId, input.name);
      await assertCampusSlugAvailable(input.slug);

      try {
        return await prisma.campus.create({ data: input });
      } catch (err) {
        if (isUniqueConstraintError(err)) {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: formatUniqueErrorMessage(err.meta),
          });
        }
        throw err;
      }
    }),

  // Get all campuses for an organization
  getByOrganization: protectedProcedure
    .input(z.object({ organizationId: z.string() }))
    .query(async ({ input, ctx }) => {
      const user = await prisma.user.findUnique({
        where: { id: ctx.userId },
        include: { permissions: true },
      });
      if (!user) {
        throw new TRPCError({ code: "UNAUTHORIZED", message: "User not found" });
      }

      if (user.role === "SUPER_ADMIN" || user.organizationId === input.organizationId) {
        // pass - all staff members in the organization can view campus lists
      } else {
        throw new TRPCError({
          code: "FORBIDDEN",
          message: "You don't have permission to view campuses for this organization",
        });
      }

      return prisma.campus.findMany({
        where: { organizationId: input.organizationId, deletedAt: null },
        orderBy: [
          { displayOrder: "asc" },
          { name: "asc" },
        ],
        include: { reps: true },
      });
    }),

  // Get a single campus by ID
  getById: protectedProcedure
    .input(z.object({ id: z.string() }))
    .query(async ({ input, ctx }) => {
      const campus = await prisma.campus.findUnique({ where: { id: input.id }, include: { reps: true } });
      if (!campus || campus.deletedAt) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Campus not found" });
      }
      await assertOrgAdminOrCampusRep(ctx, campus.organizationId, campus.id);
      return campus;
    }),

  // Update a campus
  update: protectedProcedure
    .input(z.object({
      id: z.string(),
      data: campusSchema.partial(),
    }))
    .mutation(async ({ input, ctx }) => {
      const campus = await prisma.campus.findUnique({ where: { id: input.id } });
      if (!campus || campus.deletedAt) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Campus not found" });
      }
      await assertOrgAdmin(ctx, campus.organizationId);

      const { organizationId, ...rest } = input.data;

      if (rest.name && rest.name !== campus.name) {
        await assertCampusNameAvailable(campus.organizationId, rest.name, campus.id);
      }
      if (rest.slug && rest.slug !== campus.slug) {
        await assertCampusSlugAvailable(rest.slug, campus.id);
      }

      try {
        return await prisma.campus.update({ where: { id: input.id }, data: rest });
      } catch (err) {
        if (isUniqueConstraintError(err)) {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: formatUniqueErrorMessage(err.meta),
          });
        }
        throw err;
      }
    }),

  // Delete a campus (soft delete — recoverable from Trash for 60 days; cascades
  // to this campus's Registrations, which move to Trash alongside it)
  delete: protectedProcedure
    .input(z.object({ id: z.string() }))
    .mutation(async ({ input, ctx }) => {
      const campus = await prisma.campus.findUnique({ where: { id: input.id } });
      if (!campus || campus.deletedAt) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Campus not found" });
      }
      await assertOrgAdmin(ctx, campus.organizationId);

      const now = new Date();
      return prisma.$transaction(async (tx) => {
        await tx.registration.updateMany({
          where: { campusId: input.id, deletedAt: null },
          data: { deletedAt: now },
        });
        return tx.campus.update({ where: { id: input.id }, data: { deletedAt: now } });
      }, { timeout: 15000 });
    }),

  // Get campus reps for a campus
  getCampusReps: protectedProcedure
    .input(z.object({ campusId: z.string() }))
    .query(async ({ input, ctx }) => {
      const campus = await prisma.campus.findUnique({
        where: { id: input.campusId },
        include: { reps: true },
      });
      if (!campus || campus.deletedAt) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Campus not found" });
      }
      await assertOrgAdminOrCampusRep(ctx, campus.organizationId, campus.id);
      return campus.reps;
    }),

  // Any active user in the org is eligible to be a Campus Rep — a Teacher or
  // Volunteer can hold Campus Rep capability alongside their primary role, so
  // this deliberately isn't narrowed to role === "CAMPUS_REPRESENTATIVE".
  listRepCandidates: protectedProcedure
    .input(z.object({ organizationId: z.string() }))
    .query(async ({ input, ctx }) => {
      await assertOrgAdmin(ctx, input.organizationId);
      return prisma.user.findMany({
        where: {
          organizationId: input.organizationId,
          deletedAt: null,
          role: { in: ["SUPER_ADMIN", "OWNER", "ADMIN", "CAMPUS_REPRESENTATIVE", "TEACHER"] }
        },
        select: { id: true, email: true, firstName: true, lastName: true, role: true },
        orderBy: [{ firstName: "asc" }, { email: "asc" }],
      });
    }),

  // Update campus reps (admin-only - reps do not reassign themselves/others)
  updateCampusReps: protectedProcedure
    .input(z.object({
      campusId: z.string(),
      repIds: z.array(z.string()),
    }))
    .mutation(async ({ input, ctx }) => {
      const campus = await prisma.campus.findUnique({
        where: { id: input.campusId },
        include: { reps: true },
      });
      if (!campus || campus.deletedAt) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Campus not found" });
      }
      await assertOrgAdmin(ctx, campus.organizationId);

      const currentRepIds = campus.reps.map((rep) => rep.id);
      const repsToDisconnect = currentRepIds.filter((id) => !input.repIds.includes(id));
      const repsToConnect = input.repIds.filter((id) => !currentRepIds.includes(id));

      return prisma.campus.update({
        where: { id: input.campusId },
        data: {
          reps: {
            disconnect: repsToDisconnect.map((id) => ({ id })),
            connect: repsToConnect.map((id) => ({ id })),
          },
        },
        include: { reps: true },
      });
    }),

  // Get all campuses (for dropdowns) - scoped to an organization (was previously an unscoped bug)
  getAll: protectedProcedure
    .input(z.object({ organizationId: z.string() }).optional())
    .query(async ({ ctx, input }) => {
      const currentUser = ctx.session?.user;
      if (!currentUser) {
        throw new TRPCError({ code: "UNAUTHORIZED", message: "User not authenticated" });
      }

      // SUPER_ADMIN may omit organizationId to see every org's campuses;
      // everyone else is always scoped to their own organization.
      const organizationId =
        currentUser.role === "SUPER_ADMIN" ? input?.organizationId : currentUser.organizationId;

      if (currentUser.role !== "SUPER_ADMIN" && !organizationId) {
        throw new TRPCError({ code: "FORBIDDEN", message: "Not authorized to list campuses" });
      }

      return ctx.prisma.campus.findMany({
        where: organizationId ? { organizationId, deletedAt: null } : { deletedAt: null },
        orderBy: [
          { displayOrder: "asc" },
          { name: "asc" },
        ],
        include: { organization: true },
      });
    }),

  // Get statistics for a campus (registrations, campers, trend, status counts, quota)
  getStats: protectedProcedure
    .input(z.object({ campusId: z.string(), campId: z.string().optional() }))
    .query(async ({ input, ctx }) => {
      const campus = await prisma.campus.findUnique({
        where: { id: input.campusId },
        include: { organization: { select: { activeCampId: true } } },
      });
      if (!campus || campus.deletedAt) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Campus not found" });
      }
      await assertOrgAdminOrCampusRep(ctx, campus.organizationId, campus.id);

      const activeCampId = input.campId || campus.organization.activeCampId || undefined;
      const baseWhere: Record<string, unknown> = { campusId: input.campusId, deletedAt: null };
      if (activeCampId) baseWhere.campId = activeCampId;

      const registrationsCount = await prisma.registration.count({ where: baseWhere });
      const uniqueCampers = await prisma.registration.findMany({
        where: baseWhere,
        select: { camperId: true },
      });
      const campersCount = new Set(uniqueCampers.map((r) => r.camperId)).size;

      const statusCounts = await prisma.registration.groupBy({
        by: ["status"],
        where: baseWhere,
        _count: { _all: true },
      });
      const countsByStatus = Object.fromEntries(statusCounts.map((s) => [s.status, s._count._all]));

      let quota: number | null = null;
      let quotaFullBehavior = "CLOSE";
      let usedCount = 0;
      let approvedCount = 0;
      let percentUsed = 0;

      if (activeCampId) {
        const signupLink = await prisma.signupLink.findUnique({
          where: { campusId_campId: { campusId: input.campusId, campId: activeCampId } },
        });
        if (signupLink) {
          quota = signupLink.quota;
          quotaFullBehavior = signupLink.quotaFullBehavior;
          usedCount = await prisma.registration.count({
            where: {
              campusId: input.campusId,
              campId: activeCampId,
              deletedAt: null,
              status: { notIn: ["DRAFT", "CANCELLED", "REJECTED", "ARCHIVED"] },
            },
          });
          approvedCount = await prisma.registration.count({
            where: {
              campusId: input.campusId,
              campId: activeCampId,
              deletedAt: null,
              status: "APPROVED",
            },
          });
          if (quota > 0) {
            percentUsed = Math.min(100, Math.round((approvedCount / quota) * 100));
          }
        }
      }

      const now = new Date();
      const trend = [];
      for (let i = 11; i >= 0; i--) {
        const from = new Date(now.getFullYear(), now.getMonth() - i, 1);
        const to = new Date(now.getFullYear(), now.getMonth() - i + 1, 1);
        const count = await prisma.registration.count({
          where: {
            ...baseWhere,
            createdAt: { gte: from, lt: to },
          },
        });
        trend.push({ month: from.toISOString().slice(0, 7), count });
      }

      return {
        registrationsCount,
        campersCount,
        countsByStatus,
        quota,
        quotaFullBehavior,
        usedCount,
        approvedCount,
        percentUsed,
        trend,
      };
    }),
});
